### ISSUE TITLE
Roadmap: Extracting the core into a separate package

### ISSUE THREAD

**Issue by caendesilva** [hydephp/hyde#32]
#Roadmap: Extracting the core into a separate package 

## Abstract:
I want to extract the core source code into a separate Framework package to make it easier to maintain and update.

I think this is an important feature that needs to be done before v1.0. 

However, there needs to be some work done first.

## Todos:

- [x] We need to to make sure the proper file paths are always used. This means that when running code from a vendor directory, Hyde uses paths relative to the actual project.
- [x] We need to make resources publishable. This means that resources such as Blade files need to reside in the vendor/src, but if they exist (for example if they have been published by a command) in the project resources the custom files take precedence.
- [x] <s>Since Laravel Zero (which Hyde is based on) has a neat feature to compile into a standalone .phar executable, we should also utilise that in releases.</s> Seems like Zero is not really compatible with apps that make such heavy use of filesystems as Hyde does.

## How to help:
If you have experience in writing code like this, please leave a comment in this issue and we can coordinate!

## Update
I have now successfully managed to extract the App directory into a new package. However, I have not yet touched on resources. Adding some new todos of code that needs to be extracted.

### Code to extract
Code directories:

- [x] tests
- [x] app/Commands

Resource directories: (with stuff that may need to be publishable)

- [x] resources/
- [x] src/

### Other:

- [x] Create a facade for the main Hyde class, _added in ffbdf16_

**Comment by caendesilva** [comment]
I have now successfully managed to extract the App directory into a new package. However, I have not yet touched on resources. Updating the issue with more todos.

**Comment by caendesilva** [comment]
Created a "facade" in ffbdf16

**Comment by caendesilva** [comment]
Marking the tests as done, as I think I will keep them in this repo for now.

**Comment by caendesilva** [comment]
Config files are now publishable. However, the app does not read the files from the vendor so it is still a hard requirement for the files to be present in the app directory. However, the framework config directory serves as the source of truth and the publish command can be used to reset the app to the default values, or to merge with updates.

**Comment by caendesilva** [comment]
All tasks here are now done. Tagging a new prerelease. The documentation need to be reworked though.

**Comment by caendesilva** [comment]
Implemented in https://github.com/hydephp/hyde/releases/tag/v0.3.0-alpha
and https://github.com/hydephp/framework/releases/tag/v0.4.0-alpha
