### ISSUE TITLE
1.0 Roadmap: Add more tests

### ISSUE THREAD

**Issue by caendesilva** [hydephp/hyde#37]
Tests to add:
- [x] Full feature test for the entire build process, _added in v0.4_
- [x] Insufficient coverage for Hyde\Framework\Actions\MarkdownConverter, Torchlight integration
- [x] Insufficient coverage for HydeBuildStaticSiteCommand.php, `clean` option, purge method, NPM integrations

Edit: Removed deprecated commands

**Comment by caendesilva** [comment]
Code coverage report:

Unit tests:

- [ ] HydeServiceProvider version bindings
- [ ] GeneratesDocumentationSidebar.php	
- [ ] GeneratesNavigationMenu.php	
- [ ] GetMarkdownPostList.php	
- [ ] MarkdownConverter.php

Feature tests:

- [ ] PublishStubsCommand test does not cover 403 error
- [ ] BasePublishingCommand has generally low coverage

**Comment by caendesilva** [comment]
The current tests leaves a lot of remnants. Before entering beta/v1 we should ensure that all modified files are reset after the tests.
