### ISSUE TITLE
1.0 Roadmap: Update documentation

### ISSUE THREAD

**Issue by caendesilva** [hydephp/hyde#38]
Ready to implement:
- [x] Update documentation framework to v0.3.x
- [x] Update documentation content to v0.3.x

To do when approaching 1.0 release
- [x] Finalize docs for 1.0

**Comment by caendesilva** [comment]
All major features are now documented. From here on out I will utilize a documentation driven development process.
