### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by hydephp** [hydephp/hyde#4]
When tagging a new release, there are some things to keep in mind to keep the package dist clean and user friendly.

- [x] Make sure that the environment is set to *production* in config/app.php
- [x] Make sure that the _source directories are clean and free from test posts
- [x] Make sure the .gitignore does not contain the _source directories
- [x] Do compile the frontend assets for production so NPM is not a hard dependency.

If there is anything that should be added to this list, leave a comment!

**Comment by caendesilva** [comment]
Think I've gotten the workflow down to automatically handle all of this. Closing.
